version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/packages/store"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
    commit_message:
      prefix: "misc"
    default_labels:
      - "Action: no bump"
      - "packages/store"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "in_range"

  - package_manager: "javascript"
    directory: "/packages/store-react"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
    commit_message:
      prefix: "misc"
    default_labels:
      - "Action: no bump"
      - "packages/store-react"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "in_range"

  - package_manager: "javascript"
    directory: "/packages/store-devtools"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
    commit_message:
      prefix: "misc"
    default_labels:
      - "Action: no bump"
      - "packages/store-devtools"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "in_range"
