name: On merge

on:
  pull_request_target:
    branches: [main]
    types: [closed]

jobs:
  generate-docs:
    name: 'generate docs and push'
    runs-on: ubuntu-latest

    if: >
      github.event.pull_request.merged == true
      && contains(join(github.event.pull_request.labels.*.name), 'packages/')

    steps:
    - name: Extract package label
      id: name
      uses: actions/github-script@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const labels = context.payload.pull_request.labels
            .map(label => label.name);

          const packageLabels = labels.filter(name => name.includes('packages/'));

          console.log(`::debug ::${packageLabels.length} matching labels`);

          if (packageLabels.length > 1) {
            throw new Error('Pull request should have only one package label');
          }

          if (packageLabels.length === 1) {
            console.log(`::set-output name=package::${packageLabels[0]}`)
            return;
          }

          throw new Error('Pull request is not labeled with packages, should not be here');

    - uses: actions/checkout@v2
      with:
        ref: main
        token: ${{ secrets.TOKEN_REPO_WRITE }}

    - name: Git config
      run: |
        git config user.name "Github actions"
        git config user.email "github-actions@fp51.dev"

    - uses: fp51/actions/create-gh-pages-branch@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '14'
        cache: npm

    - name: Install
      env:
        PACKAGE: ${{ steps.name.outputs.package }}
      run: |
        cd $PACKAGE
        npm ci

    - name: Generate new docs
      id: generation
      env:
        PACKAGE: ${{ steps.name.outputs.package }}
      run: |
        cd $PACKAGE
        npm run docs

        if [ -d "docs" ];  then
          echo "::set-output name=hasDoc::true"
        else
          echo "::set-output name=hasDoc::false"
        fi

    - name: Push gh-pages
      if: steps.generation.outputs.hasDoc == 'true'
      env:
        PACKAGE: ${{ steps.name.outputs.package }}
      run: |
        cd $PACKAGE

        NAME=$(cat package.json | jq -r '.name')

        git worktree add gh-pages-content gh-pages

        mkdir -p gh-pages-content/$PACKAGE || echo Dir already exists

        cp -r docs/* gh-pages-content/$PACKAGE
        cd gh-pages-content/$PACKAGE

        git add .
        git commit -m "documentation($NAME): generate new documentation"
        git push origin gh-pages

  publish:
    name: 'create version and deploy'
    runs-on: ubuntu-latest

    needs:
    - generate-docs

    if: >
      github.event.pull_request.merged == true
      && contains(join(github.event.pull_request.labels.*.name), 'packages/')
      && (
          contains(github.event.pull_request.labels.*.name, 'Action: patch bump')
        || contains(github.event.pull_request.labels.*.name, 'Action: minor bump')
        || contains(github.event.pull_request.labels.*.name, 'Action: major bump')
        || contains(github.event.pull_request.labels.*.name, 'Action: beta bump')
      )

    steps:
    - name: Extract version label
      id: extract-labels
      uses: actions/github-script@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          // version

          const versionLabels = {
            'Action: patch bump': 'patch',
            'Action: minor bump': 'minor',
            'Action: major bump': 'major',
            'Action: beta bump': 'beta',
          };

          const versionLabelsNames = Object.keys(versionLabels);

          const labels = context.payload.pull_request.labels
            .map(label => label);

          const versionLabelsPresent = labels
            .filter(label => versionLabelsNames.includes(label.name));

          console.log(`::debug ::${versionLabelsPresent.length} matching version labels`);

          if (versionLabelsPresent.length > 1) {
            throw new Error('Pull request should have only one version label');
          }

          if (versionLabelsPresent.length === 0) {
            throw new Error('Pull request should have one version label');
          }

          const versionBump = versionLabels[versionLabelsPresent[0].name];

          console.log(`::set-output name=versionBump::${versionBump}`)

          // package

          const packageLabels = labels.filter(label => label.name.includes('packages/'));

          console.log(`::debug ::${packageLabels.length} matching package labels`);

          if (packageLabels.length > 1) {
            throw new Error('Pull request should have only one package label');
          }

          if (packageLabels.length === 0) {
            throw new Error('Pull request is not labeled with packages, should not be here');
          }

          console.log(`::set-output name=package::${packageLabels[0].name}`)

    - name: Bump classic version
      if: steps.extract-labels.outputs.versionBump != 'beta'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.TOKEN_NPM }}
        BUMP_TYPE: ${{ steps.extract-labels.outputs.versionBump }}
        PACKAGE: ${{ steps.extract-labels.outputs.package }}
      run: |
        cd $PACKAGE

        VERSION=$(cat package.json | jq -r '.version')

        npm add --no-save remark-cli@^6.0.0 @jarrodldavis/remark-changelog-version-bump@^0.1.1

        ./node_modules/.bin/remark CHANGELOG.md -o --use @jarrodldavis/changelog-version-bump=version:\"$VERSION\"

        git add package.json CHANGELOG.md
        git commit -m "$VERSION"

        git tag "v$VERSION"

    - name: Bumb beta version
      if: steps.extract-labels.outputs.versionBump == 'beta'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.TOKEN_NPM }}
        PACKAGE: ${{ steps.extract-labels.outputs.package }}
      run: |
        cd $PACKAGE

        npm version prerelease --preid=beta

    - name: Push on main
      id: push
      env:
        PACKAGE: ${{ steps.extract-labels.outputs.package }}
      run: |
        git push
        git push --tags

        cd $PACKAGE

        VERSION=$(cat package.json | jq -r '.version')
        echo "::set-output name=version::$VERSION"

        NAME=$(cat package.json | jq -r '.name')
        echo "::set-output name=name::$NAME"

    - name: Extract release changelog
      id: extract-changelog
      if: steps.extract-labels.outputs.versionBump != 'beta'
      env:
        PACKAGE: ${{ steps.extract-labels.outputs.package }}
        VERSION: ${{ steps.push.outputs.VERSION }}
      run: |
        cd $PACKAGE

        VERSION_PART=$(sed -n "/## \[$VERSION\]/,/## \[/{/## \[/d;p;}" CHANGELOG.md)

        VERSION_PART="${VERSION_PART//'%'/'%25'}"
        VERSION_PART="${VERSION_PART//$'\n'/'%0A'}"
        VERSION_PART="${VERSION_PART//$'\r'/'%0D'}"
        echo VERSION_PART=$VERSION_PART

        echo "::set-output name=version-part::$VERSION_PART"

    - name: Create tarball
      env:
        PACKAGE: ${{ steps.extract-labels.outputs.package }}
        VERSION_BUMP: ${{ steps.extract-version-label.outputs.versionBump }}
        VERSION: ${{ steps.push.outputs.version }}
      run: |
        cd $PACKAGE

        PACKAGE=$(npm pack)

        mv $PACKAGE package.tgz

        NPM_TAG=$([ $VERSION_BUMP == "beta" ] && echo 'beta' || echo 'latest')

        echo $NPM_TAG > npm-tag
        echo v$VERSION > ref

    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: |
          ${{ steps.packages.outputs.packages }}/package.tgz
          ${{ steps.packages.outputs.packages }}/ref
          ${{ steps.packages.outputs.packages }}/npm-tag

    - name: Create Release
      if: steps.extract-labels.outputs.versionBump != 'beta'
      uses: actions/github-script@v2
      env:
        NAME: ${{ steps.push.outputs.NAME }}
        VERSION: ${{ steps.push.outputs.version }}
        BODY: ${{ steps.extract-changelog.outputs.version-part }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: `${process.env.NAME}@${process.env.VERSION}`,
            body: process.env.BODY,
            draft: false,
            prerelease: false,
          })
